# Generated by Django 2.2.11 on 2020-03-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRegistrationSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(verbose_name='remarks')),
                ('registration_profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='_registration_defaultregistrationsupplement_supplement', to='registration.RegistrationProfile', verbose_name='registration profile')),
            ],
        ),
    ]
